services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  JambageCom\TtProducts\:
    resource: '../Classes/*'
    exclude: '../Classes/Middleware/*,../Classes/UserFunc/*,../Classes/Api/*'

  JambageCom\TtProducts\Domain\Model\Dto\EmConfiguration:
    arguments:
      $extensionKey: 'tt_products'
    public: true

  JambageCom\TtProducts\EventListener\PageContentPreviewRenderingListener:
    tags:
      - name: event.listener
        identifier: 'ttproductsCodeListener'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
